name       : py
version    : 1.7.0
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/p/py/py-1.7.0.tar.gz : bf92637198836372b520efcba9e020c330123be8ce527e535d185ed4b6f45694
license    : MIT
component  : programming.python
summary    : Modular python support library
description: |
    The py lib is a Python development support library featuring the following tools and modules:

    py.path: uniform local and svn path objects
    py.apipkg: explicit API control and lazy-importing
    py.iniconfig: easy parsing of .ini files
    py.code: dynamic code generation and introspection
builddeps  :
    - pkgconfig(libsvn_client)  # check
    - pkgconfig(python3)
    - python-pytest             # check
    - python-setuptools
    - python-setuptools-scm
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test pytest -k"-test_warning"
    %python3_test pytest3 -k"-test_warning"
