name       : py
version    : 1.4.33
release    : 1
source     :
    - https://pypi.python.org/packages/2a/a5/139ca93a9ffffd9fc1d3f14be375af3085f53cc490c508cf1c988b886baa/py-1.4.33.tar.gz : 1f9a981438f2acc20470b301a07a496375641f902320f70e31916fe3377385a9
license    : MIT
component  : programming.python
summary    : Modular python support library
description: |
    The py lib is a Python development support library featuring the following tools and modules:
    
    py.path: uniform local and svn path objects
    py.apipkg: explicit API control and lazy-importing
    py.iniconfig: easy parsing of .ini files
    py.code: dynamic code generation and introspection
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
setup      : |
    %python_setup
install    : |
    %python_install
check:
    python setup.py test
