name       : py
version    : 1.5.3
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/p/py/py-1.5.3.tar.gz : 29c9fab495d7528e80ba1e343b958684f4ace687327e6f789a94bf3d1915f881
license    : MIT
component  : programming.python
summary    : Modular python support library
description: |
    The py lib is a Python development support library featuring the following tools and modules:

    py.path: uniform local and svn path objects
    py.apipkg: explicit API control and lazy-importing
    py.iniconfig: easy parsing of .ini files
    py.code: dynamic code generation and introspection
builddeps  :
    - pkgconfig(libsvn_client)  # check
    - pkgconfig(python3)
    - python-pytest             # check
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    export LC_ALL="en_US.UTF-8"

    pushd $PKG_BUILD_DIR/py2build
        PYTHONPATH=$PWD py.test -k"-test_warning"
    popd

    pushd $PKG_BUILD_DIR/py3build
        PYTHONPATH=$PWD py.test3 -k"-test_warning"
    popd
