name       : py
version    : 1.8.0
release    : 10
source     :
    - https://files.pythonhosted.org/packages/f1/5a/87ca5909f400a2de1561f1648883af74345fe96349f34f737cdfc94eba8c/py-1.8.0.tar.gz : dc639b046a6e2cff5bbe40194ad65936d6ba360b52b3c3fe1d08a82dd50b5e53
license    : MIT
component  : programming.python
summary    : Modular python support library
description: |
    The py lib is a Python development support library featuring the following tools and modules:

    py.path: uniform local and svn path objects
    py.apipkg: explicit API control and lazy-importing
    py.iniconfig: easy parsing of .ini files
    py.code: dynamic code generation and introspection
builddeps  :
    - pkgconfig(libsvn_client)  # check
    - pkgconfig(python3)
    - python-pytest             # check
    - python-setuptools
    - python-setuptools-scm
setup      : |
    %patch -p1 < $pkgfiles/fix-pytest4-compatibility-errors.patch
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test pytest -k"-test_warning"
    %python3_test pytest3 -k"-test_warning"
